### ISSUE TITLE
False Positive: XP.apple.com

### ISSUE THREAD

**Issue by Thomas-Schubert** [badmojr/1Hosts#1178]
Please remove this domain from the blocklist as it keeps my HomePod from working. See also here: https://support.apple.com/HT210060

**Comment by hagezi** [comment]
See: https://github.com/badmojr/1Hosts/search?q=xp.apple.com&type=issues

**Comment by hagezi** [comment]
@Thomas-Schubert 

https://youtu.be/8JxvH80Rrcw
https://gizmodo.com/apple-iphone-analytics-tracking-even-when-off-app-store-1849757558

`xp.apple.com` is tracking, however blocking it causes problems with some updates. Apparently not always and not for everyone. Some iOS updates could not be downloaded, the last update went without problems. With watchOS updates I had problems every time, I had to unblock xp.apple.com.

Because it is tracking, it is blocked in aggressive/strict lists. In my lists only in the Ultimate version. In 1Hosts from the Pro version. So when using strict lists it is something for personal whitelist. I unblock it only when updates are pending and these can not be installed.

Since I do not own a Homepod, what does not work by blocking. Would be interesting to know.

Regards,
Gerd

**Comment by yokoffing** [comment]
@hagezi I didn’t realize you blocked it in Ultimate; I figured it was allowlisted in all lists because it breaks updates.

Good to know!
