### ISSUE TITLE
Possible problem with ||media-lab.ai^ in 1Hosts Pro

### ISSUE THREAD

**Issue by alxthaman** [badmojr/1Hosts#276]
Hello!

I have an occasional issue while browsing imgur where sometimes a page won't load and I get a blank page instead.

I believe **||media-lab.ai^** is the culprit.

When I add **@@||js.media-lab.ai/wana.2.0.8.js$script,domain=imgur.com** to my filters, the problem disappears.

For some reason, most images on imgur are fine, and only some are affected.

Here's a bunch of them :

https://imgur.com/gallery/CoqLnHe
https://imgur.com/gallery/EDeRvIf
https://imgur.com/gallery/0jH2hen
https://imgur.com/gallery/IpzIuLW

**Comment by badmojr** [comment]
My guess is they have started blocking adblock users, considering the domain in question is sourced from https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt & has been listed since  `Aug 15 2020`.

See:
https://blocklist-tools.developerdan.com/entries/search?q=js.media-lab.ai
https://www.reddit.com/r/pihole/comments/qc17ey/pihole_blocking_all_of_imgur_if_you_have/

cc: @lightswitch05

**Comment by badmojr** [comment]
Here are a couple of sites that actively use the above domain and work just fine.
https://publicwww.com/websites/%22js.media-lab.ai%22/
