### ISSUE TITLE
Windows data domains

### ISSUE THREAD

**Issue by MaXfAa** [badmojr/1Hosts#780]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [ ] Lite
- [x] Pro
- [ ] Xtra
<br>

**Client:**
NextDNS

<br>

**Domains:**
```
settings.data.microsoft.com
```
<br>

**Details:**
The Pro list blocks "settings-win.data.microsoft.com" but doesn't block "settings.data.microsoft.com"... 🤔 
![image](https://user-images.githubusercontent.com/71935156/197250183-7dc21815-13ad-4b14-b430-976addb01be5.png)

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by spirillen** [comment]
That could very well be caused by the fact of blacklisting `settings.data.microsoft.com` is known to make false claims for having this subdomain whitelisted, as in windows 10, this is used while checking for privacy downgrades (windows update)

- https://mypdns.org/mypdns/support/-/issues/683
- https://mypdns.org/my-privacy-dns/matrix/-/issues/3137

**Comment by badmojr** [comment]
Been to know to severely intefere with Windows's Settings app. As far as I know, this isn't tracking/telemetry, but rather configuration related.
See also: https://learn.microsoft.com/en-us/windows/privacy/manage-windows-1809-endpoints

**Comment by MaXfAa** [comment]
@badmojr ??
