### ISSUE TITLE
Block consensu.org and s0.2mdn.net

### ISSUE THREAD

**Issue by royerlraph79** [badmojr/1Hosts#907]
<br>
<h2 align="center">Submit Form</h2>
<div align="center">
  Get your issue resolved quickly! Fill in the form accurately.
</div>

**Lists in use:**
- [ ] mini
- [x] Lite
- [x] Pro
- [x] Xtra
<br>

**Client: AdGuard Pro for iOS and for Mac**

<br>

**Domains:**
```
s0.2mdn.net
consensu.org
```
<br>

**Details:**

<div align="center">
  <h2>Thank you for supporting 1Hosts.</h2>
  <sub>It’s people like you who make these lists great! ❤<ub>
</div>

**Comment by royerlraph79** [comment]
Not planned? At least add s0.2mdn.net, it’s literally one of the basic ones 😳 also, you already block s1.2mdn.net, so why not that one?

By the way, consensu.org is a third-party cookie domain. Your decision is irrational.

**Comment by crssi** [comment]
@royerlraph79 AFAIK blocking `consensu.org` will break sites functionality.
I have tried to block on a few dozens of users and I have got a revolting fire back.
So, I had to back off, otherwise no-one (of my users) would use my implementation for protection.

I know that there are also reports of breakages when blocking `s0.2mdn.net`, but I have not encounter any and it might also be true that is not applicable anymore.

NOTE: This are solely my observations and has nothing to do with @badmojr opinion.

Cheers
